"""Regenerate src/data/logSchema.js from the workbook's log sheets (row-5 headers + dropdown lists).
Run from the kit folder:  .venv/bin/python prototype/scripts/gen_log_schema.py [path/to/KartikRaj_R2_Annexure.xlsx]"""
import json, os, re, sys
from openpyxl import load_workbook
from openpyxl.utils import column_index_from_string, get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
xl = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', '..', 'out', 'KartikRaj_R2_Annexure.xlsx')
wb = load_workbook(xl)
out = {}
for key, name in [('merchant', 'R2 Validation Log'), ('distributor', 'Distributor Log')]:
    ws = wb[name]
    heads = [c.value for c in ws[5] if c.value is not None]
    opts = {}
    for dv in ws.data_validations.dataValidation:
        col = re.match(r'([A-Z]+)', str(dv.sqref)).group(1)
        opts[column_index_from_string(col) - 1] = dv.formula1.strip('"').split(',')
    out[key] = dict(sheet=name, firstRow=6, columns=[dict(col=get_column_letter(i + 1), name=h, options=opts.get(i)) for i, h in enumerate(heads)])
js = ("// GENERATED by prototype/scripts/gen_log_schema.py from out/KartikRaj_R2_Annexure.xlsx "
      "(row 5 headers + data-validation lists). Do not hand-edit.\n")
js += "export const LOG_SCHEMA = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
open(os.path.join(HERE, '..', 'src', 'data', 'logSchema.js'), 'w').write(js)
print({k: len(v['columns']) for k, v in out.items()})
